### ISSUE TITLE
CTC CPMI formula in the paper

### ISSUE THREAD

**Issue by corneliusjustin** [hamedR96/CTC#2]
Hi, I want to ask regarding the formula u given in the paper:
![image](https://github.com/hamedR96/CTC/assets/70965816/27a9360e-e2ce-45ed-9d6a-b834a02351d8)
Based on this formula, u use combination rather than permutation right? which means if I have topic $t = [bad. good]$ it will calculate the CPMI("good", "bad" | sentence) but it never calculate CPMI("bad", "good" | sentence), where those two are not equivalent. But in the code u use permutation for calculating the CPMI, hence whether CPMI("good", "bad" | sentence) or CPMI("bad", "good" | sentence) are considered in the final result of CTC. Whereas in the paper, the latter is not considered? Is there something wrong in the paper formula or am I misunderstood? Thanks

**Comment by hamedR96** [comment]
Hi Justin, 
CTC CPMI uses combination to calculate coherence score. However, according to (Hoover et al. 2021), to calculate CPMI("good", "bad) in a sentence, we need to calculate both CPMI("bad", "good" | sentence) and CPMI("good", "bad" | sentence) and later make average since the values are not equivalent. The reason behind are explained in details in "Linguistic Dependencies and Statistical Dependence".
